### ISSUE TITLE
A few questions...

### ISSUE THREAD

**Issue by seamusdemora** [lslqtz/bclm_loop#1]
My Mac is Ventura 13.7. `bclm` worked through 13.6.9, but after todays' upgrade, it is _kaput_. 

I've "installed" via `sudo cp ~/Downloads/bclm_loop /usr/local/bin && sudo chmod 755 /usr/local/bin/bclm_loop`; 
"Optimized Battery Charging" is OFF.

There was a note in the README I didn't understand : 

>Just create a new plist in /Library/LaunchDaemons

Can you explain **how** to do that, please? 

I tried running from the cmd line:

```zsh
sudo bclm_loop loop
Use software-based battery level limits. (SMCKey "CHWA" not found)
Limit status will be changed. (Current: true, Last: false)
Charging status has changed! (Current: false, Last: nil)
SMC has opened!
Limit status has changed! (Limit)
MagSafe LED status has changed! (Full)
SMC has closed!
SMC has opened!
Limit status has changed! (Limit)
MagSafe LED status has changed! (Full)
SMC has closed!
SMC has opened!
Limit status has changed! (Limit)
MagSafe LED status has changed! (Full)
SMC has closed!
^C
``` 

That seemed to be going nowhere. Since then, I've tried this:

```zsh
% sudo bclm_loop persist 
%
```

But nothing seems to be happening - I guess maybe b/c of the **plist** I've not created ? 

I wonder: I use a program called `LaunchControl` - could I create a system daemon to run `bclm_loop` **instead of** a plist?

**Comment by lslqtz** [comment]
This command will create the launchdaemon for you.

Try ```ls /Library/LaunchDaemon | grep -i com.lslqtz.bclm_loop```.

**Comment by seamusdemora** [comment]
> This command `sudo bclm_loop persist` will create the launchdaemon for you.
> 
> Try to see if it is there: `ls /Library/LaunchDaemons | grep -i com.lslqtz.bclm_loop`.

Yes - it's there. I wonder why bclm_loop ***appears*** to be doing nothing?

**Comment by lslqtz** [comment]
> > This command `sudo bclm_loop persist` will create the launchdaemon for you.
> > Try to see if it is there: `ls /Library/LaunchDaemons | grep -i com.lslqtz.bclm_loop`.
> 
> Yes - it's there. I wonder why bclm_loop _**appears**_ to be doing nothing?

When it does not detect a power adapter change, it will not take action, but will silently detect (in the background). It will be executed three times when it is first started or when the power adapter is changed to ensure that it is as effective as possible.

**Comment by seamusdemora** [comment]
> > Yes - it's there. I wonder why bclm_loop _**appears**_ to be doing nothing?
> 
> When it does not detect a power adapter change, it will not take action, but will silently detect (in the background). It will be executed three times when it is first started or when the power adapter is changed to ensure that it is as effective as possible. Silent detection is to avoid excessive and useless logging. 

OK - it's been nearly 24 hours; the led on the adapter plug is still green, and the battery icon in the "menu bar" (?) still says 100% charge. After posting my question above, I briefly turned "Optimized Battery Charging" ON - and then back to OFF. 

What constitutes a "power adapter change"?

> When you execute the `sudo bclm_loop persist` command, it will complete silently without any prompt. This seems to be a behavior of the original version as well. If nothing is displayed, it means it succeeded.

Yes - that's the command I've entered: `sudo bclm_loop persist`. 

But note the parenthetical message I got in the first line when I ran `sudo bclm_loop loop`: 

`(SMCKey "CHWA" not found)`  ...  that doesn't *sound good*, but it may mean nothing? I just wanted to make sure you'd seen it. 

So what do you think I should do? Re-boot, or ... ???



> Just try to see if the charge limit works even after a reboot (it may not work briefly during the reboot process because the battery is no longer taken over by the system and bclm_loop).

**Comment by lslqtz** [comment]
> OK - it's been nearly 24 hours; the led on the adapter plug is still green, and the battery icon in the "menu bar" (?) still says 100% charge. After posting my question above, I briefly turned "Optimized Battery Charging" ON - and then back to OFF.
> 
> What constitutes a "power adapter change"?
> 
> >



> > > Yes - it's there. I wonder why bclm_loop _**appears**_ to be doing nothing?
> > 
> > 
> > When it does not detect a power adapter change, it will not take action, but will silently detect (in the background). It will be executed three times when it is first started or when the power adapter is changed to ensure that it is as effective as possible. Silent detection is to avoid excessive and useless logging.
> 
> OK - it's been nearly 24 hours; the led on the adapter plug is still green, and the battery icon in the "menu bar" (?) still says 100% charge. After posting my question above, I briefly turned "Optimized Battery Charging" ON - and then back to OFF.
> 
> What constitutes a "power adapter change"?
> 
> > When you execute the `sudo bclm_loop persist` command, it will complete silently without any prompt. This seems to be a behavior of the original version as well. If nothing is displayed, it means it succeeded.
> 
> Yes - that's the command I've entered: `sudo bclm_loop persist`.
> 
> But note the parenthetical message I got in the first line when I ran `sudo bclm_loop loop`:
> 
> `(SMCKey "CHWA" not found)` ... that doesn't _sound good_, but it may mean nothing? I just wanted to make sure you'd seen it.
> 
> So what do you think I should do? Re-boot, or ... ???
> 
> > Just try to see if the charge limit works even after a reboot (it may not work briefly during the reboot process because the battery is no longer taken over by the system and bclm_loop).
> 
> I've just checked my system w/ `LaunchControl` (see attached screen shot); it shows `bclm_loop` is running, but still _nothing happening_??
> 
> <img alt="Screenshot 2024-09-29 at 5 48 53 PM" width="1212" src="https://private-user-images.githubusercontent.com/14911811/371899379-4cb33554-876f-4103-97f3-cb3b478f1291.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2NjcxOTgsIm5iZiI6MTcyNzY2Njg5OCwicGF0aCI6Ii8xNDkxMTgxMS8zNzE4OTkzNzktNGNiMzM1NTQtODc2Zi00MTAzLTk3ZjMtY2IzYjQ3OGYxMjkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDAzMjgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiMTMxOTc2Nzg3YjI3MTdjYzNkM2ZjMjVlNWI4YWIxNzBhMTlhYzA5MGNhNmI0ZDI3YjEwYjQ5NGMyMjlmMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ryRVjocKq1XxU_9iJJ4tWPSN2ikHF3WN0LCOofEsGM0">

For first use, you need to manually discharge it to 80%.

What CHWA can't find are technical details, but what it does show is the previous sentence: only software-based charging limits can be used.

**Comment by seamusdemora** [comment]
@lslqtz : 

> For first use, you need to manually discharge it to 80%. It does not have a forced discharge function, because this function will make the system unable to recognize the adapter, which makes the charging status unintuitive. The firmware limitation does not have this disadvantage, but it cannot be applied in some high-version systems and firmware due to technical limitations.
> 
> The fact that chwa cannot be found is a technical detail, indicating that only software-based charge limits can be applied.
> 
> What constitutes an adapter change? Simply unplug or plug in your power cord...

AHH-H-H !! So I first need to manually discharge it to 80%. OK, I can do that. May I assume a little more or less than 80% is OK?? 

Thanks!

**Comment by lslqtz** [comment]
> @lslqtz :
> 
> > For first use, you need to manually discharge it to 80%. It does not have a forced discharge function, because this function will make the system unable to recognize the adapter, which makes the charging status unintuitive. The firmware limitation does not have this disadvantage, but it cannot be applied in some high-version systems and firmware due to technical limitations.
> > The fact that chwa cannot be found is a technical detail, indicating that only software-based charge limits can be applied.
> > What constitutes an adapter change? Simply unplug or plug in your power cord...
> 
> AHH-H-H !! So I first need to manually discharge it to 80%. OK, I can do that. May I assume a little more or less than 80% is OK??
> 
> Thanks!

I recommend a bit less than 80%, this might be a documentation bug, I'll put this note in README.md to prevent problems.

**Comment by lslqtz** [comment]
> The "manual discharge" to 78% worked fine for me on macOS Ventura 13.7. `bclm-loop` appears to be working pretty much as expected. Something else you might want to add to your documentation is a note stating that the LED on the MagSafe connector is "Green" in color - this might confuse some who have come from `bclm`.
> 
> I noticed you've released a new version. Does this new version also have the requirement to "manually" get the battery below 80% before `bclm-loop` will begin functioning? In any case, the new release sounds very interesting - I'll look forward to trying it.

Yes, but usually the update takes less time, so the charge control should not be interrupted for too long. If a higher percentage is acceptable (not necessarily 100%), then you can ignore it.

Thanks for the suggestion, I have adjusted the documentation and indicated that it will adjust the MagSafe LED to green when fully charged.
